version: "3.8"

services:
  jenkins:
    container_name: jenkins
    build:
      context: ./jenkins
      dockerfile: jenkins.Dockerfile
    ports:
      - "8889:8080"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock

  db :
    image: mysql:8.0.40
    container_name: mysql_h5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: zig2m6hS
      MYSQL_DATABASE: h5
      MYSQL_USER: mysql_h5
      MYSQL_PASSWORD: 6cN0A5Fl
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network

  java_service:
    build:
      context: ./java_service
    container_name: java17_h5
    restart: unless-stopped
    ports:
      - "8443:8443"
    environment:
      - DB_HOST=mysql_h5
      - DB_PORT=3306
      - DB_USER=mysql_h5
      - DB_PASSWORD=6cN0A5Fl
      - SERVER_URL=https://hi-five.site
      - MAIL_USERNAME=noreply.mail.h5@gmail.com
      - MAIL_PASSWORD=ghsnycgzibikbkpk
      - OPENVIDU_URL=https://hi-five.site/openvidu
      - OPENVIDU_SECRET=rz7FazDNZkSqkJmr
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/h5/uploads/profile
      - /etc/letsencrypt:/owncert:ro
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/nginx/ssl:ro
    depends_on:
      - java_service
      - db
      - redis
      - mongo
    networks:
      - app-network

volumes:
  db_data:
  mongo_data:

networks:
  app-network:
    driver: bridge

