version: "3.8"

services:
  java_service:
    image: project_java_service:latest
    container_name: java17_h5
    restart: unless-stopped
    ports:
      - "8443:8443"
    environment:
      - DB_HOST=mysql_h5
      - DB_PORT=3306
      - DB_USER=mysql_h5
      - DB_PASSWORD=6cN0A5Fl
      - SERVER_URL=https://hi-five.site
      - MAIL_USERNAME=noreply.mail.h5@gmail.com
      - MAIL_PASSWORD=ghsnycgzibikbkpk
      - OPENVIDU_URL=https://hi-five.site/openvidu
      - OPENVIDU_SECRET=rz7FazDNZkSqkJmr
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/h5/uploads/profile
      - /etc/letsencrypt:/owncert:ro
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/nginx/ssl:ro
    depends_on:
      - java_service
      - db
      - redis
      - mongo
    networks:
      - app-network

volumes:
  db_data:
  mongo_data:

networks:
  app-network:
    driver: bridge
