version: "3.8"
services:
  java_service:
    image: project_java_service:latest
    container_name: java_service
    restart: unless-stopped
    ports:
      - "8443:8443"
    # DB, 인증서 등 필요한 환경변수들은 production 환경에 맞게 설정
    environment:
      - DB_HOST=mysql_h5
      - DB_PORT=3306
      - DB_USER=mysql_h5
      - DB_PASSWORD=6cN0A5Fl
      - SERVER_URL=https://hi-five.site
      - MAIL_USERNAME=noreply.mail.h5@gmail.com
      - MAIL_PASSWORD=ghsnycgzibikbkpk
      - OPENVIDU_URL=https://hi-five.site/openvidu
      - OPENVIDU_SECRET=rz7FazDNZkSqkJmr
    volumes:
      - /etc/letsencrypt:/owncert:ro
    networks:
      - app-network

  nginx:
    image: project_nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - java_service
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
